package: qpython
user: cpcloud

platform:
 - win-64
 - win-32
 - linux-64
 - linux-32
 - osx-64

engine:
 - python=2.7

before_script:
  - python -V

script:
  - conda build conda.recipe

build_targets: conda

notifications:
  email:
    recipients: ['phillip.cloud@continuum.io']
