language: python
python:
  - "2.7"

# command to install dependencies
install: pip install -r requirements.txt -U

# command to run tests
script:  
  - python setup.py build_ext --inplace
  - env PYTHONPATH=. py.test